routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::get('/', [\App\Http\Controllers\BooksController::class, 'index'])->name('books.index');

Route::prefix('auth')->name('auth.')->group(function (){
    Route::get('register', [\App\Http\Controllers\UsersController::class, 'registerForm'])->name('register-form');
    Route::post('register', [\App\Http\Controllers\UsersController::class, 'store'])->name('register');

    Route::get('login', [\App\Http\Controllers\SessionsController::class, 'loginForm'])->name('login-form');
    Route::post('login', [\App\Http\Controllers\SessionsController::class, 'store'])->name('login');
    Route::delete('log-out', [\App\Http\Controllers\SessionsController::class, 'destroy'])->name('logout');

    Route::get('users/{user}', [\App\Http\Controllers\UsersController::class, 'show'])->name('show');
    Route::get('applications/{book}', [\App\Http\Controllers\ApplicationsController::class, 'create'])->name('create.application');
    Route::post('store', [\App\Http\Controllers\ApplicationsController::class, 'store'])->name('store.application');
    Route::get('return-book/{application_id}', [\App\Http\Controllers\ApplicationsController::class, 'returnBook'])->name('return.book');
    Route::get('users', [\App\Http\Controllers\UsersController::class, 'index'])->name('users.index');

});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class User extends Model
{
    use HasFactory;

    protected $fillable = ['first_name' , 'last_name', 'third_name', 'address', 'passport_number', 'password', 'library_card_number'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function application()
    {
        return $this->belongsTo(Application::class);
    }

}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\RegisterRequest;
use App\Models\Application;
use App\Models\User;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class UsersController extends AuthController
{

    /**
     * @return \Illuminate\Contracts\Foundation\Application|Factory|View|\Illuminate\Foundation\Application
     */
    public function index()
    {
        if(session()->exists('user_id')){
            $user_id = auth_user()->id;
            $applications = Application::where('user_id', $user_id)->get();
            return view('users.index', compact('applications'));
        }
        return view('sessions.create');
    }


    /**
     * @param Request $request
     * @return \Illuminate\Contracts\Foundation\Application|Factory|View|\Illuminate\Foundation\Application|RedirectResponse
     */
    public function registerForm(Request $request)
    {
        if($request->session()->exists('user_id')){
            return redirect()->route('books.index')->with('error', 'You are already register!');
        }
        return view('users.register');
    }


    /**
     * @param RegisterRequest $request
     * @return RedirectResponse
     */
    public function store(RegisterRequest $request)
    {
        $validated = $request->validated();
        $validated['password'] = Hash::make($validated['password']);
        $validated['library_card_number'] = $this->generateLibraryCartNum();
        session()->put('library_card_number', $validated['library_card_number']);

        $user = User::create($validated);
        $this->logIn($user);

        return redirect()->route('auth.show', compact('user'))->with('success', 'Registration successfully!');
    }

    /**
     * @param User $user
     * @return \Illuminate\Contracts\Foundation\Application|Factory|View|\Illuminate\Foundation\Application
     */
    public function show(User $user)
    {
        return view('users.show', compact('user'));
    }



    /**
     * @return string
     */
    function generateLibraryCartNum(): string
    {
        $characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $random_string = '';
        $length = 10;

        for ($i = 0; $i < $length; $i++) {
            $random_index = mt_rand(0, strlen($characters) - 1);
            $random_string .= $characters[$random_index];
        }

        return $random_string;
    }
}

resources/views/users/index.blade.php
@extends('layouts.base')

@section('content')

    <div class="row">
        <div class="col">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Title</th>
                    <th scope="col">Author</th>
                    <th scope="col">Return date</th>
                    <th scope="col">Status</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach($applications as $application)
                    <tr>
                        <div class="row">
                            <div class="col">
                                <td>{{$application->id}}</td>
                                <td>{{$application->book->title}}</td>
                                <td>{{$application->book->author}}</td>
                                <td>{{$application->return_date}}</td>
                                <td>{{$application->return_status}}</td>
                                @if($application->return_status == 'Ожидается' || $application->return_status == 'Просрочено')
                                    <td>
                                        <div class="row">
                                            <div class="col">
                                                <a href="{{ route('auth.return.book', ['application_id' => $application->id]) }}"
                                                   class="btn btn-primary">return book</a>
                                            </div>
                                        </div>
                                    </td>
                                @else
                                    <td></td>
                                @endif
                            </div>
                        </div>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>

@endsection

resources/views/users/register.blade.php
@extends('layouts.base')

@section('content')
    <div class="row">
        <div class="col-6 offset-3 align-self-center">
            @include('notifications.alerts')
            <h1 class="text-center mt-5">Register</h1>
            <hr>
            <form action="{{route('auth.register')}}" method="post">
                @csrf
                <div class="form-group">
                    <label for="first_name">First Name</label>
                    <input type="text" class="form-control" id="first_name" name="first_name">
                </div>
                <div class="form-group">
                    <label for="last_name">Last Name</label>
                    <input type="text" class="form-control" id="last_name" name="last_name">
                </div>
                <div class="form-group">
                    <label for="third_name">Third Name</label>
                    <input type="text" class="form-control" id="third_name" name="third_name">
                </div>
                <div class="form-group">
                    <label for="address">Address</label>
                    <input type="text" class="form-control" id="address" name="address">
                </div>
                <div class="form-group">
                    <label for="passport_number">Passport Number</label>
                    <input type="text" class="form-control" id="passport_number" name="passport_number">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" name="password">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword2">Confirm password</label>
                    <input type="password" class="form-control" id="exampleInputPassword2" name="password_confirmation">
                </div>
                <div class="mt-2">
                    <button type="submit" class="btn btn-outline-primary">Get a library card</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/users/show.blade.php
@extends('layouts.base')
@section('content')

    <h1>Hello {{ $user->last_name }}</h1>
    <p><b>Library card number: </b>{{ $user->library_card_number }}</p>

@endsection