routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::get('/', [\App\Http\Controllers\BooksController::class, 'index'])->name('books.index');

Route::prefix('auth')->name('auth.')->group(function (){
    Route::get('register', [\App\Http\Controllers\UsersController::class, 'registerForm'])->name('register-form');
    Route::post('register', [\App\Http\Controllers\UsersController::class, 'store'])->name('register');

    Route::get('login', [\App\Http\Controllers\SessionsController::class, 'loginForm'])->name('login-form');
    Route::post('login', [\App\Http\Controllers\SessionsController::class, 'store'])->name('login');
    Route::delete('log-out', [\App\Http\Controllers\SessionsController::class, 'destroy'])->name('logout');

    Route::get('users/{user}', [\App\Http\Controllers\UsersController::class, 'show'])->name('show');
    Route::get('applications/{book}', [\App\Http\Controllers\ApplicationsController::class, 'create'])->name('create.application');
    Route::post('store', [\App\Http\Controllers\ApplicationsController::class, 'store'])->name('store.application');
    Route::get('return-book/{application_id}', [\App\Http\Controllers\ApplicationsController::class, 'returnBook'])->name('return.book');
    Route::get('users', [\App\Http\Controllers\UsersController::class, 'index'])->name('users.index');

});

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    use HasFactory;

    protected $fillable = ['picture', 'author', 'title', 'genre_id'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function genre()
    {
        return $this->belongsTo(Genre::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function application()
    {
        return $this->hasOne(Application::class);
    }

}

app/Http/Controllers/BooksController.php
<?php

namespace App\Http\Controllers;

use App\Models\Book;
use App\Models\Genre;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class BooksController extends Controller
{
    /**
     * @return Application|Factory|View|\Illuminate\Foundation\Application
     */
    public function index()
    {
       $genres = Genre::with('books')->paginate(2);
       return view('books.index', compact('genres'));
    }

}

resources/views/books/index.blade.php
@extends('layouts.base')
@section('content')

    @foreach($genres as $genre)

        <h3><b>Genre: </b>{{$genre->name}}</h3>
        <div class="row">
            @foreach($genre->books as $book)
                <div class="card mb-3" style="max-width: 540px;">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <img class="card-img-top" style="width: 100px; height: 100px"
                                 src="{{asset('/storage/' . $book->picture)}}" alt="{{ $book->picture}}">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title mt-2">Title: {{$book->title}}</h5>
                                <p class="card-text">Author: {{$book->author}}</p>
                                @if($book->application)
                                    @if($book->application->return_status === 'Ожидается' || $book->application->return_status == 'Просрочено')
                                        <p>Book taken before {{ $book->application->return_date }}</p>
                                    @elseif($book->application->return_status === 'Возвращено')
                                        <p class="card-text"><a href="{{ route('auth.create.application', $book) }}" class="btn btn-outline-secondary">Get the book</a></p>
                                    @endif
                                @else
                                    <p class="card-text"><a href="{{ route('auth.create.application',  $book) }}" class="btn btn-outline-secondary">Get the book</a></p>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    @endforeach

    <div class="justify-content-md-center p-5">
        <div class="col-md-auto">
            {{ $genres->links() }}
        </div>
    </div>


@endsection