routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::get('/', [\App\Http\Controllers\BooksController::class, 'index'])->name('books.index');

Route::prefix('auth')->name('auth.')->group(function (){
    Route::get('register', [\App\Http\Controllers\UsersController::class, 'registerForm'])->name('register-form');
    Route::post('register', [\App\Http\Controllers\UsersController::class, 'store'])->name('register');

    Route::get('login', [\App\Http\Controllers\SessionsController::class, 'loginForm'])->name('login-form');
    Route::post('login', [\App\Http\Controllers\SessionsController::class, 'store'])->name('login');
    Route::delete('log-out', [\App\Http\Controllers\SessionsController::class, 'destroy'])->name('logout');

    Route::get('users/{user}', [\App\Http\Controllers\UsersController::class, 'show'])->name('show');
    Route::get('applications/{book}', [\App\Http\Controllers\ApplicationsController::class, 'create'])->name('create.application');
    Route::post('store', [\App\Http\Controllers\ApplicationsController::class, 'store'])->name('store.application');
    Route::get('return-book/{application_id}', [\App\Http\Controllers\ApplicationsController::class, 'returnBook'])->name('return.book');
    Route::get('users', [\App\Http\Controllers\UsersController::class, 'index'])->name('users.index');

});

app/Models/Application.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Application extends Model
{
    use HasFactory;

    protected $fillable = ['user_id', 'book_id', 'return_date', 'return_status'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function book()
    {
        return $this->belongsTo(Book::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function users()
    {
        return $this->hasMany(User::class);
    }


}

app/Http/Controllers/ApplicationsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ApplicationRequest;
use App\Models\Application;
use App\Models\Book;
use App\Models\User;
use Illuminate\Http\Request;

class ApplicationsController extends Controller
{

    /**
     * @param Book $book
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Foundation\Application
     * @throws \Psr\Container\ContainerExceptionInterface
     * @throws \Psr\Container\NotFoundExceptionInterface
     */
    public function create(Book $book)
    {
        if(session()->exists('library_card_number')) {
            $library_card_number = session()->get('library_card_number');
        } else {
            $library_card_number = null;
        }

        return view('applications.create', compact('book', 'library_card_number'));
    }


    /**
     * @param ApplicationRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(ApplicationRequest $request)
    {

        $user = User::where('library_card_number', $request->library_card_number)->first();

        $application = new Application();
        $application->book_id = $request->input('book_id');
        $application->user_id = $user->id;
        $application->return_date = $request->input('return_date');
        $application->return_status = 'Ожидается';
        $application->save();
        return redirect()->route('books.index')->with('success', "The book was successfully taken!!!");

    }


    /**
     * @param $applicationId
     * @return \Illuminate\Http\RedirectResponse
     */
    public function returnBook($applicationId)
    {
        $application = Application::find($applicationId);
        $application->return_status = 'Возвращено';
        $application->return_date = now()->format('d-m-Y');
        $application->save();
        return redirect()->back()->with('success', 'The book was successfully returned!');

    }
}

resources/views/applications/create.blade.php
@extends('layouts.base')
@section('content')

    <div class="row">
        <div class="col-6 offset-3 align-self-center">
            @include('notifications.alerts')
            <h1 class="text-center">Applying for a book</h1>
            <hr>
            <form action="{{route('auth.store.application')}}" method="post">
                @csrf
                <input type="hidden" class="form-control" id="book_id" name="book_id" value="{{ $book->id }}">
                <div class="form-group">
                    <label for="library_card_number">Library card</label>
                    <input type="text" class="form-control" id="library_card_number"
                           @if(!is_null($library_card_number)) value="{{ $library_card_number }}" readonly
                           @endif name="library_card_number">
                </div>
                <div class="form-group">
                    <label for="author">Author</label>
                    <input type="text" class="form-control" id="author" name="author" value="{{ $book->author }}"
                           readonly>
                </div>
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" class="form-control" id="title" name="title" value="{{ $book->title }}" readonly>
                </div>
                <div class="form-group">
                    <label for="return_date">Return Date</label>
                    <input type="date" class="form-control" id="return_date" name="return_date">
                </div>
                <div class="mt-2">
                    <button type="submit" class="btn btn-primary">Apply now</button>
                </div>
            </form>
        </div>
    </div>

@endsection