routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::get('/', [\App\Http\Controllers\BooksController::class, 'index'])->name('books.index');

Route::prefix('auth')->name('auth.')->group(function (){
    Route::get('register', [\App\Http\Controllers\UsersController::class, 'registerForm'])->name('register-form');
    Route::post('register', [\App\Http\Controllers\UsersController::class, 'store'])->name('register');

    Route::get('login', [\App\Http\Controllers\SessionsController::class, 'loginForm'])->name('login-form');
    Route::post('login', [\App\Http\Controllers\SessionsController::class, 'store'])->name('login');
    Route::delete('log-out', [\App\Http\Controllers\SessionsController::class, 'destroy'])->name('logout');

    Route::get('users/{user}', [\App\Http\Controllers\UsersController::class, 'show'])->name('show');
    Route::get('applications/{book}', [\App\Http\Controllers\ApplicationsController::class, 'create'])->name('create.application');
    Route::post('store', [\App\Http\Controllers\ApplicationsController::class, 'store'])->name('store.application');
    Route::get('return-book/{application_id}', [\App\Http\Controllers\ApplicationsController::class, 'returnBook'])->name('return.book');
    Route::get('users', [\App\Http\Controllers\UsersController::class, 'index'])->name('users.index');

});

resources/views/layouts/base.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Homework 62</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Scripts -->
    @vite(['resources/sass/app.scss', 'resources/js/app.js'])

</head>
<body>

<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">Home</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>


        <a class="nav-link" href="{{ route('auth.users.index') }}">My books</a>

        <div class="user-head" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav me-auto">

            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ms-auto">
                <!-- Authentication Links -->
                @if(is_null(auth_user()))
                    {{--                    @if (Route::has('login-form'))--}}-
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('auth.login-form') }}">Login</a>
                    </li>
                    {{--                    @endif--}}

                    {{--                    @if (Route::has('register'))--}}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('auth.register-form') }}">Register</a>
                    </li>
                    {{--                    @endif--}}
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                           data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ auth_user()->last_name }}
                        </a>

                        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('auth.logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">Logout</a>

                            <form id="logout-form" action="{{ route('auth.logout') }}" method="POST" class="d-none">
                                @csrf
                                @method('delete')

                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>
<div class="flex-center position-ref full-height">
    <div class="content container-sm">
        @yield('content')
    </div>
</div>
</body>
</html>